[package]
name = "solving-physics"
version = "0.1.0"
description = ""
authors = ["Yegor Knyazev"]
repository = "https://github.com/yegorweb/solving-physics"
categories = ["components"]
disciplines = [
  "chemistry", "education", "physics",
]
keywords = [
  "physics", "school", "task", "solving",
]
entrypoint = "lib.typ"
license = "MIT"